import {
  UPSTREAM_HTTP_ADDRESS,
  UPSTREAM_HTTP_PORT,
  UPSTREAM_HTTP_SAFE_PORT,
  UPSTREAM_INSTALL_METHOD,
} from './utils'

/**
 * Generate the contents of config.js — the file CryptPad's Node server
 * reads at startup. We write this to the subcontainer rootfs at
 * /cryptpad/config/config.js on every restart; the upstream entrypoint's
 * `[ ! -f "$CPAD_CONF" ]` guard (verified in docker-entrypoint.sh@2026.5.1)
 * means our pre-written file bypasses the entrypoint's auto-generation
 * branch entirely.
 *
 * Path overrides (filePath, blobPath, …) point at /data/* — the volume
 * mount. taskPath is included because upstream's config.example.js@2026.5.1
 * lists it; the prior attempt missed it, leaving CryptPad's scheduled-task
 * storage at the upstream relative default (./data/tasks → resolved against
 * /cryptpad as cwd → ephemeral rootfs path = lost on container rebuild).
 *
 * Hardcoded preservation of httpAddress and installMethod: upstream's
 * docker-entrypoint.sh sets these via sed when generating from scratch.
 * Since we bypass the entrypoint via CPAD_CONF, we set them ourselves.
 *
 * NOT overridden:
 *   - websocketPort: upstream default 3003 is what we want.
 *   - disableIntegratedEviction: upstream default (false, eviction enabled)
 *     is what we want.
 *   - maxUploadSize, adminEmail, etc: managed via CryptPad's in-app
 *     /admin/ panel.
 */
export interface CryptpadConfigInputs {
  /** httpUnsafeOrigin — full origin (scheme://host[:port]) of the main UI. */
  httpUnsafeOrigin: string
  /** httpSafeOrigin — full origin of the sandbox iframe. */
  httpSafeOrigin: string
  /** Public signing keys mirrored into config.js's adminKeys array. */
  adminKeys: string[]
}

export function generateCryptpadConfig(inputs: CryptpadConfigInputs): string {
  const adminKeysJs =
    inputs.adminKeys.length === 0
      ? ''
      : '\n' +
        inputs.adminKeys.map((k) => `    ${JSON.stringify(k)}`).join(',\n') +
        '\n  '
  return `/* CryptPad config — auto-generated by StartOS on every restart. Do not edit;
 * any local changes are overwritten when the service restarts. Configuration
 * lives in StartOS actions and CryptPad's in-app /admin/ panel.
 */
module.exports = {
  httpUnsafeOrigin: ${JSON.stringify(inputs.httpUnsafeOrigin)},
  httpSafeOrigin:   ${JSON.stringify(inputs.httpSafeOrigin)},

  httpAddress:   ${JSON.stringify(UPSTREAM_HTTP_ADDRESS)},
  httpPort:      ${UPSTREAM_HTTP_PORT},
  httpSafePort:  ${UPSTREAM_HTTP_SAFE_PORT},

  installMethod: ${JSON.stringify(UPSTREAM_INSTALL_METHOD)},

  filePath:        '/data/datastore/',
  archivePath:     '/data/archive/',
  pinPath:         '/data/pins/',
  blockPath:       '/data/block/',
  blobPath:        '/data/blob/',
  blobStagingPath: '/data/blobstage/',
  taskPath:        '/data/tasks/',
  decreePath:      '/data/decrees/',
  logPath:         '/data/logs/',
  logToStdout:     true,

  adminKeys: [${adminKeysJs}],
}
`
}
